name: build and push cloudflare-ddns image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Set up Docker Buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@master
        with:
          version: latest
      
      - name: Login to DockerHub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login --username ${{ secrets.DOCKER_USERNAME }} --password-stdin
      
      - name: Run Buildx
        run: |
          docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t tcousin/cloudflare-ddns:latest -t tcousin/cloudflare-ddns:$GITHUB_SHA --push . 
